[project]
name = "authentik-appliances"
version = "0.1.0"
description = ""
dependencies = [
    "ansible>=11.2.0,<12.0.0"
]

[project.optional-dependencies]
dev = [
    "ansible-lint>=25.1.3,<26.0.0"
]

[build-system]
requires = ["uv>=0.1.0"]
build-backend = "uv"