- hosts: all

  vars:
    pip_install_packages:
      - name: docker==6.1.3
      - name: requests==2.31.0
      - name: docker-compose
    docker_install_compose: true
    docker_daemon_options:
      live-restore: true
      log-opts:
        max-size: "100m"
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    # - name: Install additional packages
    #   apt:
    #     name:
    #       - docker-ce
    #       - docker-compose-v2
    #     state: present
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - goauthentik.appliance
