- hosts: all

  vars:
    pip_install_packages:
      - name: docker
    docker_edition: 'ce'
    docker_packages:
      - "docker-{{ docker_edition }}"
      - "docker-{{ docker_edition }}-cli"
      #- "docker-{{ docker_edition }}-rootless-extras"
    docker_packages_state: present
    docker_install_compose_plugin: true
    docker_compose_package: docker-compose-plugin
    docker_compose_package_state: present
    docker_install_compose: true
    docker_compose_path: /usr/local/bin/docker-compose
    docker_daemon_options:
      live-restore: true
      log-opts:
        max-size: "100m"
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - goauthentik.appliance
