- name: authentik | Firewall | Allow SSH
  community.general.ufw:
    rule: allow
    name: OpenSSH
- name: authentik | Firewall | HTTP(s)
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - '80'
    - '443'
- name: authentik | Firewall | Enable
  community.general.ufw:
    state: enabled
    policy: allow
